name: Deploy to Azure Storage

on:
  push:
    branches:
      - main  # or your preferred branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to Azure Storage
        run: |
          az storage blob upload-batch \
          --connection-string ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }} \
          --source ./ \
          --destination \$web \
          --overwrite
