name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' # Use 'temurin' for Adoptium or 'zulu' for Azul Zulu JDK
        #cache: 'maven' # Optional: You can use cache if you are using Maven

    - name: Install SonarScanner
      run: |
        curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
        unzip sonar-scanner.zip -d $HOME
        export PATH="$HOME/sonar-scanner-4.7.0.2747-linux/bin:$PATH"

    - name: Run SonarQube Scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -D"sonar.projectKey=Tourism-web" \
          -D"sonar.sources=." \
          -D"sonar.host.url=http://192.168.159.134:9000" \
          -D"sonar.login=${{ secrets.SONAR_TOKEN }}"
