name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # or your preferred branch

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2.0.0
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}

      - name: Install dependencies
        run: npm install  # Adjust based on your project setup

      - name: Run SonarCloud analysis
        run: |
          npx sonar-scanner \
          -Dsonar.projectKey=SANTOSH146_Kerala-Tourism-Website-main  # Replace with your actual project key
          -Dsonar.organization=santosh146  # Your organization key
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
